# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 245635ce1b4061228b317cc3edc70c5809d7ca975420bc4b90cf471d297ae54db8476ca8f6e5212e897e669163c80e9bbf0ae67fc6ec7051e5b6a554af2185a2

test:
  secret_key_base: 200b7b5d363012ace94947875487551124f2fe5089a612bf978a31b86bffd3e7111f6b5cbfc98dbdb19ed6613e9043c5b131bcec6ba716cd94e947751e3adfdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
